services:
  app:
    container_name: petclinic-app
    image: jenkins-pet
    ports:
      - "99:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    container_name: petclinic-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - petclinic-vol-sql:/var/lib/mysql
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5
volumes:
  petclinic-vol-sql:

